Footer and Governors Modifcation
tsg-iitkgp/tsg-site pull request #13
Opened 2021-04-02 20:23 UTC by Praneeth-rdy

## Files Changed
1) Markdown files in societies directory
2) Footer's scss and component

2021-04-02 20:41 UTC, sahil-shubham requested changes
I have left some comments, everything else looks good. Thanks for this PR.

2021-04-02 20:41 UTC, sahil-shubham commented on styles/_footer.scss
>    padding: 1rem;
There are two padding properties, we can remove the padding altogether as it's creating a width issue in mobile view.

2021-04-02 20:41 UTC, sahil-shubham commented on styles/_footer.scss
> +      margin-right: 4vw;
better to define margin in terms of `rem`

2021-04-02 20:41 UTC, sahil-shubham commented on societies/swg.md
> -Governors: <br />
Could you remove the image from this file. We will add it again when we have some.

2021-04-03 03:29 UTC, Praneeth-rdy commented
I have made the necessary changes. Check the last commit once.

2021-04-03 04:00 UTC, sahil-shubham approved these changes
Looks good to me, there is some padding issue but I will fix it in future PRs. Thanks.

2021-04-03 04:00 UTC, merged